// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;
import 'package:objective_c/objective_c.dart' as objc;
import 'package:ffi/ffi.dart' as pkg_ffi;

late final _class_UIApplication = objc.getClass("UIApplication");
late final _sel_isKindOfClass_ = objc.registerName("isKindOfClass:");
final _objc_msgSend_19nvye5 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Bool Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      bool Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
typedef instancetype = ffi.Pointer<objc.ObjCObjectImpl>;
typedef Dartinstancetype = objc.ObjCObject;
late final _sel_sharedApplication = objc.registerName("sharedApplication");
final _objc_msgSend_151sglz = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCObjectImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
late final _sel_applicationIconBadgeNumber = objc.registerName(
  "applicationIconBadgeNumber",
);
final _objc_msgSend_1hz7y9r = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Long Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      int Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
late final _sel_setApplicationIconBadgeNumber_ = objc.registerName(
  "setApplicationIconBadgeNumber:",
);
final _objc_msgSend_4sp4xj = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Long,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        int,
      )
    >();
late final _sel_init = objc.registerName("init");
late final _sel_new = objc.registerName("new");
late final _sel_allocWithZone_ = objc.registerName("allocWithZone:");
final _objc_msgSend_1cwp428 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.NSZone>,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCObjectImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.NSZone>,
      )
    >();
late final _sel_alloc = objc.registerName("alloc");

/// UIApplication
extension type UIApplication._(objc.ObjCObject object$)
    implements objc.ObjCObject, objc.NSObject {
  /// Constructs a [UIApplication] that points to the same underlying object as [other].
  UIApplication.as(objc.ObjCObject other) : object$ = other {
    assert(isA(object$));
  }

  /// Constructs a [UIApplication] that wraps the given raw object pointer.
  UIApplication.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [UIApplication].
  static bool isA(objc.ObjCObject obj) => _objc_msgSend_19nvye5(
    obj.ref.pointer,
    _sel_isKindOfClass_,
    _class_UIApplication,
  );

  /// alloc
  static UIApplication alloc() {
    final $ret = _objc_msgSend_151sglz(_class_UIApplication, _sel_alloc);
    return UIApplication.fromPointer($ret, retain: false, release: true);
  }

  /// allocWithZone:
  static UIApplication allocWithZone(ffi.Pointer<objc.NSZone> zone) {
    final $ret = _objc_msgSend_1cwp428(
      _class_UIApplication,
      _sel_allocWithZone_,
      zone,
    );
    return UIApplication.fromPointer($ret, retain: false, release: true);
  }

  /// new
  static UIApplication new$() {
    final $ret = _objc_msgSend_151sglz(_class_UIApplication, _sel_new);
    return UIApplication.fromPointer($ret, retain: false, release: true);
  }

  /// sharedApplication
  static UIApplication sharedApplication() {
    final $ret = _objc_msgSend_151sglz(
      _class_UIApplication,
      _sel_sharedApplication,
    );
    return UIApplication.fromPointer($ret, retain: true, release: true);
  }

  /// Returns a new instance of UIApplication constructed with the default `new` method.
  UIApplication() : this.as(new$().object$);
}

extension UIApplication$Methods on UIApplication {
  /// applicationIconBadgeNumber
  int get applicationIconBadgeNumber {
    return _objc_msgSend_1hz7y9r(
      object$.ref.pointer,
      _sel_applicationIconBadgeNumber,
    );
  }

  /// init
  UIApplication init() {
    objc.checkOsVersionInternal(
      'UIApplication.init',
      iOS: (false, (2, 0, 0)),
      macOS: (false, (10, 0, 0)),
    );
    final $ret = _objc_msgSend_151sglz(
      object$.ref.retainAndReturnPointer(),
      _sel_init,
    );
    return UIApplication.fromPointer($ret, retain: false, release: true);
  }

  /// setApplicationIconBadgeNumber:
  set applicationIconBadgeNumber(int value) {
    _objc_msgSend_4sp4xj(
      object$.ref.pointer,
      _sel_setApplicationIconBadgeNumber_,
      value,
    );
  }
}
